---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "AFCMS"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "AFCMS"

